<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeApp.Business\EmployeeApp.Application.csproj" />
    <ProjectReference Include="..\EmployeeApp.Dal\EmployeeApp.Infrastructure.csproj" />
  </ItemGroup>


</Project>
