name: Master Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildBE:
    name: Build BE
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  buildFE:
    name: Build FE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./EmployeeApp.Web

    steps:
    - uses: actions/checkout@v2
    - name: Setup Angular
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.x'
    - name: test script
      run: npm run dev
    - name: Install NPM
      run: npm install
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
